UnbanJob:
  every: 5m
  class: UnbanJob
  queue: medium
  description: Clears expired bans.

UserBucketJob:
  every: 12h
  class: UserBucketJob
  queue: low
  description: Categorizes users according to activity.
